### ISSUE TITLE
Fatal Exception in Network Change Event Not Completely Exiting

### ISSUE THREAD

**Issue by kalahari** [kalahari/DnsDirector#3]
On a fatal/unhandled exception in a network change event handler, the service hangs when stopping.

```
2016-04-17 22:04:23,036 [26] INFO  DnsDirector.Service.Network [(null)] - Network_NetworkAddressChanged()
2016-04-17 22:04:23,037 [26] INFO  DnsDirector.Service.Network [(null)] - Refreshing DHCP DNS resolvers
2016-04-17 22:04:24,252 [26] INFO  DnsDirector.Service.Network [(null)] - Iterating 4 IP enabled interfaces
2016-04-17 22:04:24,252 [26] INFO  DnsDirector.Service.Network [7] - Description: Intel(R) Ethernet Connection I217-LM
2016-04-17 22:04:24,252 [26] INFO  DnsDirector.Service.Network [7] - Clearing resolvers on interface
2016-04-17 22:04:24,252 [26] INFO  DnsDirector.Service.Network [7] - Setting DNS resolvers: null
2016-04-17 22:04:24,381 [26] ERROR DnsDirector.Service.Network [7] - Error setting DNS servers
System.Exception: DNSServerSearchOrder got result: 94, expected: 0, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa393295
   at DnsDirector.Service.Network.SetDnsResolvers(ManagementObject adapter, IEnumerable`1 resolvers) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 207
2016-04-17 22:04:24,389 [26] ERROR DnsDirector.Service.Network [(null)] - Unhandled exception on network availability change.
System.AggregateException: One or more errors occurred. ---> System.Exception: DNSServerSearchOrder got result: 94, expected: 0, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa393295
   at DnsDirector.Service.Network.SetDnsResolvers(ManagementObject adapter, IEnumerable`1 resolvers) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 211
   at DnsDirector.Service.Network.<>c__DisplayClass14_0.<PollInterfaces>b__0(AdapterConfig cfg) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 98
   at DnsDirector.Service.Network.EachInterface(Action`1 handleInterface) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 185
   at DnsDirector.Service.Network.<PollInterfaces>d__14.MoveNext() in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DnsDirector.Service.Network.NetworkChanged() in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 66
---> (Inner Exception #0) System.Exception: DNSServerSearchOrder got result: 94, expected: 0, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa393295
   at DnsDirector.Service.Network.SetDnsResolvers(ManagementObject adapter, IEnumerable`1 resolvers) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 211
   at DnsDirector.Service.Network.<>c__DisplayClass14_0.<PollInterfaces>b__0(AdapterConfig cfg) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 98
   at DnsDirector.Service.Network.EachInterface(Action`1 handleInterface) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 185
   at DnsDirector.Service.Network.<PollInterfaces>d__14.MoveNext() in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 84<---

2016-04-17 22:04:24,390 [26] FATAL DnsDirector.Service.Service [(null)] - Fatal exception on service event
System.AggregateException: One or more errors occurred. ---> System.Exception: DNSServerSearchOrder got result: 94, expected: 0, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa393295
   at DnsDirector.Service.Network.SetDnsResolvers(ManagementObject adapter, IEnumerable`1 resolvers) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 211
   at DnsDirector.Service.Network.<>c__DisplayClass14_0.<PollInterfaces>b__0(AdapterConfig cfg) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 98
   at DnsDirector.Service.Network.EachInterface(Action`1 handleInterface) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 185
   at DnsDirector.Service.Network.<PollInterfaces>d__14.MoveNext() in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DnsDirector.Service.Network.NetworkChanged() in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 66
---> (Inner Exception #0) System.Exception: DNSServerSearchOrder got result: 94, expected: 0, see: https://msdn.microsoft.com/en-us/library/windows/desktop/aa393295
   at DnsDirector.Service.Network.SetDnsResolvers(ManagementObject adapter, IEnumerable`1 resolvers) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 211
   at DnsDirector.Service.Network.<>c__DisplayClass14_0.<PollInterfaces>b__0(AdapterConfig cfg) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 98
   at DnsDirector.Service.Network.EachInterface(Action`1 handleInterface) in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 185
   at DnsDirector.Service.Network.<PollInterfaces>d__14.MoveNext() in C:\projects\dnsdirector\DnsDirector.Service\Network.cs:line 84<---

2016-04-17 22:04:24,391 [23] INFO  DnsDirector.Service.Service [(null)] - OnStop()
2016-04-17 22:04:24,501 [57] INFO  DnsDirector.Service.Network [(null)] - Network_NetworkAvailabilityChanged()
2016-04-17 22:04:24,501 [57] INFO  DnsDirector.Service.Network [(null)] - Network change reaction disabled.
2016-04-17 22:04:24,502 [57] INFO  DnsDirector.Service.Network [(null)] - Network_NetworkAddressChanged()
2016-04-17 22:04:24,502 [57] INFO  DnsDirector.Service.Network [(null)] - Network change reaction disabled.
```

**Comment by kalahari** [comment]
The retry logic has mitigated this issue.
